name: "Chess"

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'test|')
    steps:

    - name: Set env vars
      run: |
        echo "REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1

    - name: Play
      run: |
        ruby -e "puts 'hello from Ruby.'"
        ruby -e "puts ENV['REPOSITORY']"
        ruby <<- EORUBY
          hi mum.
EORUBY
