name: Add `/shipit` comment

on:
  pull_request_review:
#    branches:
#      - 'dependabot/**'

jobs:
  shipit_job:
    runs-on: ubuntu-latest
    steps:
    - name: Add comment to Pull Request
      # if: github.event.review.state == 'approved'
      run: |
        echo ${{ github.event.review.state }}
        curl --request POST \
          --data '{"body": "reviewed"}' \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
